//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Kingrice.Models.UmbracoCmsContent
{
	/// <summary>Testimonial</summary>
	[PublishedModel("testimonial")]
	public partial class Testimonial : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new const string ModelTypeAlias = "testimonial";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Testimonial, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Testimonial(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Fb Profile Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("fbProfileLink")]
		public string FbProfileLink => this.Value<string>("fbProfileLink");

		///<summary>
		/// Google Profile Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("googleProfileLink")]
		public string GoogleProfileLink => this.Value<string>("googleProfileLink");

		///<summary>
		/// Instagram Profile Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("instagramProfileLink")]
		public string InstagramProfileLink => this.Value<string>("instagramProfileLink");

		///<summary>
		/// Testimonial BIO
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("testimonialBIO")]
		public string TestimonialBio => this.Value<string>("testimonialBIO");

		///<summary>
		/// Testimonial Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("testimonialName")]
		public string TestimonialName => this.Value<string>("testimonialName");

		///<summary>
		/// Testimonial Photo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("testimonialPhoto")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent TestimonialPhoto => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("testimonialPhoto");

		///<summary>
		/// Testimonial Position
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("testimonialPosition")]
		public string TestimonialPosition => this.Value<string>("testimonialPosition");

		///<summary>
		/// Twitter Profile Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("twitterProfileLink")]
		public string TwitterProfileLink => this.Value<string>("twitterProfileLink");
	}
}
